spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mytest
    password: lzj20050101FZ
    url: jdbc:mysql://112.124.36.59:3306/mytest?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
